/**
 * Deterministic PDF report generation — no AI involved (see CLAUDE.md / CLIENT_BUILD_PLAN.md
 * Phase 5). The team report draws simple vector primitives with jsPDF, staying crisp and
 * reproducible. The player-profile exports (exportAthletePdf/exportRosterPdf) instead embed a
 * rasterized capture of the same radar/trend charts shown on the live athlete page — Josh asked
 * these to "mimic the page with the graphs instead of just numbers and text," with a white
 * background for print (see src/lib/reports/chartCapture.js) — so "deterministic" here means
 * same data in → same image out every time, not "no images allowed."
 *
 * Only one exporter module for MVP (team + athlete share this file) instead of the reference
 * project's five separate ones — see CLIENT_BUILD_PLAN.md Phase 2.
 */
import { jsPDF } from 'jspdf'
import { getActiveMetrics, getMetric } from '../metrics.js'
import { buildTeamKpi, getTeamAthletes, getMetricsWithAthleteData } from '../selectors.js'
import { resolveBrandColors } from '../theme.js'
import { captureAthleteCharts } from './chartCapture.js'

const PAGE_MARGIN = 14
const PAGE_WIDTH_MM = 210
const PAGE_HEIGHT_MM = 297

function hexToRgbTuple(hex) {
  const clean = hex.replace('#', '')
  const full = clean.length === 3 ? clean.split('').map((c) => c + c).join('') : clean.padEnd(6, '0')
  const num = parseInt(full, 16)
  return [(num >> 16) & 255, (num >> 8) & 255, num & 255]
}

/**
 * Draws a team/org-branded header bar so exports "adjust automatically" with the same
 * palette as the on-screen dashboard — see src/lib/theme.js.
 */
function drawHeader(doc, { title, subtitle, team, org }) {
  const { primary } = resolveBrandColors({ team, org })
  const [r, g, b] = hexToRgbTuple(primary)
  doc.setFillColor(r, g, b)
  doc.rect(0, 0, PAGE_WIDTH_MM, 4, 'F')

  doc.setFontSize(16)
  doc.setTextColor(20, 20, 20)
  doc.text(title, PAGE_MARGIN, 18)
  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text(subtitle, PAGE_MARGIN, 25)
  doc.setDrawColor(220, 220, 220)
  doc.line(PAGE_MARGIN, 29, PAGE_WIDTH_MM - PAGE_MARGIN, 29)
}

function drawFooter(doc) {
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text(
    'Generated by Performance Hub — preliminary build. Thresholds shown are placeholders, not confirmed sport-science guidance.',
    PAGE_MARGIN,
    290,
  )
}

/**
 * Team averages report — deliberately averages-only (not a per-athlete dump, which already
 * lives in Individual Athlete Reports / Player Profiles) per Josh's feedback: this is meant as
 * the quick "where's the team at" snapshot, not a duplicate of the roster detail available
 * elsewhere. `metricKeys` is coach-selected (see ReportPanel.jsx's metric picker) rather than a
 * fixed set, so the loop below has a page-break guard — the old fixed 4-metric version never
 * needed one, but a coach picking most of the full battery now can.
 */
export function exportTeamPdf({ org, team, store, metricKeys, reportTitle, recipient }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const metrics = (metricKeys?.length ? metricKeys.map(getMetric).filter(Boolean) : getActiveMetrics())
  const title = reportTitle?.trim() || `${team.name} — Team Report`
  const subtitleParts = [org.name, team.sport, `Generated ${new Date().toLocaleDateString()}`]
  if (recipient?.trim()) subtitleParts.unshift(`For: ${recipient.trim()}`)
  drawHeader(doc, { title, subtitle: subtitleParts.join(' · '), team, org })

  let y = 40
  doc.setFontSize(12)
  doc.setTextColor(20, 20, 20)
  doc.text('Team averages (most recent recorded value per athlete)', PAGE_MARGIN, y)
  y += 8
  doc.setFontSize(8)
  doc.setTextColor(140, 140, 140)
  doc.text('Per-athlete detail is in Individual Athlete Reports / Player Profiles, not here.', PAGE_MARGIN, y)
  y += 8

  for (const metric of metrics) {
    const kpi = buildTeamKpi(store, team.id, metric.key)
    doc.setFontSize(10)
    doc.setTextColor(60, 60, 60)
    doc.text(
      `${metric.label}: ${kpi.average != null ? kpi.average : 'n/a'} ${metric.unit} (n=${kpi.athleteCount})`,
      PAGE_MARGIN,
      y,
    )
    y += 7
    if (y > 270) {
      drawFooter(doc)
      doc.addPage()
      y = 20
    }
  }

  drawFooter(doc)
  doc.save(`${team.name.replace(/\s+/g, '-').toLowerCase()}-team-report.pdf`)
}

/**
 * Draws one athlete's chart page onto whatever page of `doc` is currently active — shared by
 * both the single-athlete export and the whole-roster packet (exportRosterPdf below) so the two
 * never drift out of sync. Always titles the page with the athlete's own name/position (not
 * overridable per-athlete in a multi-page packet, since that's what makes each page identifiable)
 * — `recipient` still appears in the subtitle line for context. `metricKeys` is passed in rather
 * than assumed, so the single export can keep using the curated dashboard-default metrics while
 * the roster packet uses every metric that athlete actually has data for (see exportRosterPdf).
 * Always fits the captured chart image on this one page — if it would run tall (an athlete with
 * many tested metrics), it's scaled down to fit rather than spilling onto a second page, since
 * "one athlete per page" was the explicit request for the roster packet.
 */
async function drawAthletePage(doc, { org, team, athlete, store, metricKeys, recipient }) {
  const subtitleParts = [athlete.position, team.name, org.name, `Generated ${new Date().toLocaleDateString()}`].filter(Boolean)
  if (recipient?.trim()) subtitleParts.unshift(`For: ${recipient.trim()}`)
  drawHeader(doc, { title: athlete.displayName, subtitle: subtitleParts.join(' · '), team, org })

  const { dataUrl, aspectRatio } = await captureAthleteCharts({
    athlete,
    team,
    org,
    store,
    metricKeys,
    theme: 'light',
  })

  const top = 34
  const usableWidth = PAGE_WIDTH_MM - PAGE_MARGIN * 2
  const availableHeight = PAGE_HEIGHT_MM - top - 14
  let imgWidth = usableWidth
  let imgHeight = imgWidth * aspectRatio
  if (imgHeight > availableHeight) {
    imgHeight = availableHeight
    imgWidth = imgHeight / aspectRatio
  }
  const x = PAGE_MARGIN + (usableWidth - imgWidth) / 2
  doc.addImage(dataUrl, 'JPEG', x, top, imgWidth, imgHeight)

  drawFooter(doc)
}

/**
 * `metricKeys` defaults to the curated dashboard set only when the caller doesn't pass one (the
 * quick per-athlete PDF button in ReportPanel's "Individual athlete reports" list, which has no
 * metric picker of its own). AthleteDetail's own "Export PDF" button always passes its own
 * "Tests shown" toggle selection instead, so what downloads matches what's on screen.
 */
export async function exportAthletePdf({ org, team, athlete, store, recipient, metricKeys }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const keys = metricKeys?.length ? metricKeys : getActiveMetrics().map((m) => m.key)
  await drawAthletePage(doc, { org, team, athlete, store, metricKeys: keys, recipient })
  doc.save(`${athlete.displayName.replace(/\s+/g, '-').toLowerCase()}-report.pdf`)
}

/**
 * The whole-roster "packet" Josh asked for: one athlete per page, portrait, everything that
 * athlete actually has data for (not just the curated dashboard defaults — see
 * getMetricsWithAthleteData) so a page genuinely shows "all their information," not a subset.
 * Charts are captured sequentially (one athlete at a time reuses the same off-screen render
 * target) rather than in parallel — simpler and safe, and roster sizes here don't make the
 * extra time meaningful.
 */
export async function exportRosterPdf({ org, team, store, recipient }) {
  const athletes = getTeamAthletes(store, team.id)
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' })

  for (let i = 0; i < athletes.length; i++) {
    const athlete = athletes[i]
    if (i > 0) doc.addPage()
    const metricKeys = getMetricsWithAthleteData(store, athlete.id).map((m) => m.key)
    const fallbackKeys = metricKeys.length ? metricKeys : getActiveMetrics().map((m) => m.key)
    await drawAthletePage(doc, { org, team, athlete, store, metricKeys: fallbackKeys, recipient })
  }

  doc.save(`${team.name.replace(/\s+/g, '-').toLowerCase()}-player-profiles.pdf`)
}
