/**
 * PPTX export — FIRST-DRAFT LAYOUT. Josh asked for the ability to export slides but no example
 * deck or layout preference has been provided yet, so this is a plain, functional starting
 * point (title slide + KPI summary + roster table) meant to be refined together once he's seen
 * it — see CLIENT_BUILD_PLAN.md addendum and docs/OPEN_QUESTIONS.md.
 *
 * Deterministic, same data as the PDF/dashboard/CSV exports — no AI involved.
 */
import PptxGenJS from 'pptxgenjs'
import { getActiveMetrics, getMetric } from '../metrics.js'
import { buildTeamKpi } from '../selectors.js'
import { resolveBrandColors } from '../theme.js'

function hexNoHash(hex) {
  return hex.replace('#', '')
}

/**
 * Averages-only, same reasoning as exportTeamPdf in pdfExport.js — per-athlete detail already
 * lives in Individual Athlete Reports / Player Profiles, so this deck stays a quick team-level
 * snapshot instead of duplicating that. `metricKeys` is coach-selected (see ReportPanel.jsx);
 * `autoPage: true` (pptxgenjs's own overflow handling) replaces the old fixed `false` so a large
 * selection spills onto additional slides instead of getting cut off at the table's now-variable
 * row count.
 */
export function exportTeamPptx({ org, team, store, metricKeys, reportTitle, recipient }) {
  const metrics = metricKeys?.length ? metricKeys.map(getMetric).filter(Boolean) : getActiveMetrics()
  const { primary } = resolveBrandColors({ team, org })
  const pptx = new PptxGenJS()
  pptx.defineLayout({ name: 'A4_16x9', width: 10, height: 5.63 })
  pptx.layout = 'A4_16x9'

  // Title slide
  const title = pptx.addSlide()
  title.background = { color: '0a0c10' }
  title.addShape('rect', { x: 0, y: 0, w: 10, h: 0.15, fill: { color: hexNoHash(primary) } })
  title.addText(reportTitle?.trim() || team.name, {
    x: 0.5, y: 2.0, w: 9, h: 1, fontSize: 32, bold: true, color: 'FFFFFF',
  })
  const subtitleParts = [org.name, team.sport, new Date().toLocaleDateString()]
  if (recipient?.trim()) subtitleParts.unshift(`For: ${recipient.trim()}`)
  title.addText(subtitleParts.join(' · '), {
    x: 0.5, y: 2.9, w: 9, h: 0.5, fontSize: 14, color: 'A0A4B8',
  })

  // KPI summary slide(s) — autoPage lets pptxgenjs add continuation slides on its own if the
  // coach's metric selection is long enough to overflow one slide.
  const kpiSlide = pptx.addSlide()
  kpiSlide.background = { color: '111318' }
  kpiSlide.addText('Team Averages', { x: 0.5, y: 0.4, fontSize: 20, bold: true, color: 'FFFFFF' })
  kpiSlide.addText(
    'Per-athlete detail is in Individual Athlete Reports / Player Profiles, not here.',
    { x: 0.5, y: 0.85, w: 9, fontSize: 10, color: 'A0A4B8' },
  )
  const kpiRows = metrics.map((metric) => {
    const kpi = buildTeamKpi(store, team.id, metric.key)
    return [metric.label, kpi.average != null ? `${kpi.average} ${metric.unit}` : 'n/a', String(kpi.athleteCount)]
  })
  kpiSlide.addTable([['Metric', 'Average', 'Athletes'], ...kpiRows], {
    x: 0.5, y: 1.3, w: 9, fontSize: 12, color: 'E8EAF0',
    border: { type: 'solid', color: '252836', pt: 1 },
    fill: { color: '1A1D26' },
    autoPage: true,
    autoPageSlideStartY: 0.6,
    autoPageRepeatHeader: true,
    autoPageHeaderRows: 1,
  })

  kpiSlide.addText(
    'Generated by Performance Hub — preliminary build. First-draft slide layout, not yet reviewed with the client.',
    { x: 0.5, y: 5.2, w: 9, fontSize: 8, color: '6B7280' },
  )

  pptx.writeFile({ fileName: `${team.name.replace(/\s+/g, '-').toLowerCase()}-team-report.pptx` })
}
