/**
 * Player Profiles roster deck — one slide per athlete, everything that athlete actually has
 * data for (see getMetricsWithAthleteData), preceded by a title slide showing the org logo/name,
 * team name, and "Player Profiles" per Josh's spec. Each athlete slide embeds a rasterized
 * capture of the same radar + trend charts shown on the live athlete page — "mimic the page with
 * the graphs" — rendered in the app's own dark theme (unlike the PDF export, which is
 * deliberately white/print-friendly; see src/lib/reports/pdfExport.js and chartCapture.js).
 *
 * Deterministic, no AI — same as every other exporter in this folder.
 */
import PptxGenJS from 'pptxgenjs'
import { getTeamAthletes, getMetricsWithAthleteData } from '../selectors.js'
import { getActiveMetrics } from '../metrics.js'
import { resolveBrandColors } from '../theme.js'
import { captureAthleteCharts } from './chartCapture.js'

const MUTED_COLOR = 'A0A4B8'

function hexNoHash(hex) {
  return hex.replace('#', '')
}

const SLIDE_W = 10
const SLIDE_H = 5.63

export async function exportRosterPptx({ org, team, store, recipient }) {
  const { primary } = resolveBrandColors({ team, org })
  const athletes = getTeamAthletes(store, team.id)
  const pptx = new PptxGenJS()
  pptx.defineLayout({ name: 'A4_16x9', width: SLIDE_W, height: SLIDE_H })
  pptx.layout = 'A4_16x9'

  // Title slide — org logo, org name, team name, "Player Profiles" per spec.
  const title = pptx.addSlide()
  title.background = { color: '0a0c10' }
  title.addShape('rect', { x: 0, y: 0, w: SLIDE_W, h: 0.15, fill: { color: hexNoHash(primary) } })
  if (org.logoUrl) {
    title.addImage({ path: org.logoUrl, x: 0.5, y: 0.55, w: 1, h: 1 })
  }
  title.addText('Player Profiles', { x: 0.5, y: 1.9, w: 9, h: 1, fontSize: 34, bold: true, color: 'FFFFFF' })
  const subtitleParts = [org.name, team.name, new Date().toLocaleDateString()]
  if (recipient?.trim()) subtitleParts.unshift(`For: ${recipient.trim()}`)
  title.addText(subtitleParts.join(' · '), { x: 0.5, y: 2.85, w: 9, h: 0.4, fontSize: 13, color: MUTED_COLOR })

  // One slide per athlete — captured chart image, sequential (simplest/safest; roster sizes
  // here don't make parallel capture worth the added complexity).
  for (const athlete of athletes) {
    const slide = pptx.addSlide()
    slide.background = { color: '0a0c10' }
    slide.addShape('rect', { x: 0, y: 0, w: SLIDE_W, h: 0.1, fill: { color: hexNoHash(primary) } })

    const metricKeys = getMetricsWithAthleteData(store, athlete.id).map((m) => m.key)
    const fallbackKeys = metricKeys.length ? metricKeys : getActiveMetrics().map((m) => m.key)
    const { dataUrl, aspectRatio } = await captureAthleteCharts({
      athlete,
      team,
      org,
      store,
      metricKeys: fallbackKeys,
      theme: 'dark',
      layout: 'landscape',
      widthPx: 1150,
    })

    const marginX = 0.3
    const top = 0.25
    const maxWidth = SLIDE_W - marginX * 2
    const maxHeight = SLIDE_H - top - 0.2
    let w = maxWidth
    let h = w * aspectRatio
    if (h > maxHeight) {
      h = maxHeight
      w = h / aspectRatio
    }
    const x = (SLIDE_W - w) / 2
    slide.addImage({ data: dataUrl, x, y: top, w, h })
  }

  const last = pptx.addSlide()
  last.background = { color: '111318' }
  last.addText(
    'Generated by Performance Hub — preliminary build.',
    { x: 0.5, y: 2.3, w: 9, fontSize: 12, color: MUTED_COLOR, align: 'center' },
  )

  pptx.writeFile({ fileName: `${team.name.replace(/\s+/g, '-').toLowerCase()}-player-profiles.pptx` })
}
