/**
 * Weekly Coach Insight export — Josh's 2026-08-17 notes: "I'd like to be able to print out or
 * send a weekly insight for each coach of their team (with the capacity to select specific
 * players (i.e injuries or trades))."
 *
 * Deliberately lighter than the Progress Grid / Season Deck exports: no date range or stage
 * picker, since the point of a "weekly" send is "what changed since I last checked," not a
 * specific chosen comparison window — see buildWeeklyInsight in selectors.js. The one thing this
 * export adds that the others don't is athlete selection, so a coach can leave out a player who
 * was just traded or is injured without editing the whole roster.
 *
 * Deterministic, no AI. Uses jspdf-autotable, same as progressGridExport.js.
 */
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { getMetric } from '../metrics.js'
import { buildWeeklyInsight, latestDateInWeeklyInsight } from '../selectors.js'
import { resolveBrandColors } from '../theme.js'
import { formatCellValue } from './formatCell.js'

const PAGE_MARGIN = 14

const UP_COLOR = [22, 163, 74]
const DOWN_COLOR = [220, 38, 38]
const FLAT_COLOR = [100, 100, 100]

function hexToRgbTuple(hex) {
  const clean = hex.replace('#', '')
  const full = clean.length === 3 ? clean.split('').map((c) => c + c).join('') : clean.padEnd(6, '0')
  const num = parseInt(full, 16)
  return [(num >> 16) & 255, (num >> 8) & 255, num & 255]
}

function formatPct(pctChange) {
  if (pctChange == null) return 'n/a'
  const sign = pctChange > 0 ? '+' : ''
  return `${sign}${pctChange}%`
}

function directionColor(direction) {
  if (direction === 'up') return UP_COLOR
  if (direction === 'down') return DOWN_COLOR
  return FLAT_COLOR
}

export function exportWeeklyInsightPdf({ org, team, store, metricKeys, athleteIds, reportTitle, recipient }) {
  const grid = buildWeeklyInsight(store, team.id, metricKeys, athleteIds)
  const weekDate = latestDateInWeeklyInsight(grid)

  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const { primary } = resolveBrandColors({ team, org })
  const [r, g, b] = hexToRgbTuple(primary)
  const pageWidth = doc.internal.pageSize.getWidth()

  const title = reportTitle?.trim() || `${team.name} — Weekly Insight`
  const subtitleParts = [
    org.name,
    team.sport,
    weekDate ? `Week of ${weekDate}` : 'No recent data',
    `Generated ${new Date().toLocaleDateString()}`,
  ]
  if (recipient?.trim()) subtitleParts.unshift(`For: ${recipient.trim()}`)

  doc.setFillColor(r, g, b)
  doc.rect(0, 0, pageWidth, 4, 'F')
  doc.setFontSize(16)
  doc.setTextColor(20, 20, 20)
  doc.text(title, PAGE_MARGIN, 16)
  doc.setFontSize(9)
  doc.setTextColor(100, 100, 100)
  doc.text(subtitleParts.join(' · '), PAGE_MARGIN, 22)

  const head = [
    ['Athlete', ...metricKeys.flatMap((key) => {
      const metric = getMetric(key)
      return [metric?.label ?? key, '']
    })],
    ['', ...metricKeys.flatMap(() => ['Latest', 'Δ vs. last'])],
  ]

  const body = grid.map(({ athlete, metrics }) => {
    const row = [`${athlete.displayName}${athlete.position ? ` (${athlete.position})` : ''}`]
    for (const key of metricKeys) {
      const metric = getMetric(key)
      const m = metrics.find((x) => x.metricKey === key)
      row.push(formatCellValue(m?.latest, m?.latestStatus, metric?.unit))
      row.push(formatPct(m?.pctChange))
    }
    return row
  })

  autoTable(doc, {
    startY: 28,
    head,
    body,
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    styles: { fontSize: 8, cellPadding: 1.8 },
    headStyles: { fillColor: [r, g, b], textColor: 255, fontSize: 8 },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    didParseCell(data) {
      if (data.section !== 'body' || data.column.index === 0) return
      const withinGroup = (data.column.index - 1) % 2
      if (withinGroup !== 1) return // only the "Δ vs. last" sub-column gets colored
      const metricIdx = Math.floor((data.column.index - 1) / 2)
      const key = metricKeys[metricIdx]
      const row = grid[data.row.index]
      const cell = row?.metrics.find((m) => m.metricKey === key)
      if (cell?.direction) {
        data.cell.styles.textColor = directionColor(cell.direction)
        data.cell.styles.fontStyle = 'bold'
      }
    },
  })

  doc.setFontSize(7)
  doc.setTextColor(150, 150, 150)
  doc.text(
    "Generated by Performance Hub — preliminary build. Each athlete's own two most recent tests, whatever their dates — not a fixed team-wide date. Green/red indicate improvement/decline relative to the metric's own direction, not a confirmed coaching threshold.",
    PAGE_MARGIN,
    doc.internal.pageSize.getHeight() - 8,
    { maxWidth: pageWidth - PAGE_MARGIN * 2 },
  )

  doc.save(`${team.name.replace(/\s+/g, '-').toLowerCase()}-weekly-insight.pdf`)
}
